---
- name: Borrando MVs.
  hosts: localhost
  gather_facts: false

  vars_files:
    - alu01XXXXX.yaml

  vars:

    # MVs con el prefijo de la asignatura
    prefix: ID-XXXXX
    nodes:
      - name: oveja-1
      - name: oveja-2

  tasks:
    - name: Login to IaaS
      ovirt_auth:
        url: https://iaas.ull.es/ovirt-engine/api
        insecure: yes
        username: alu01XXXXX@ULL
        password: "{{ ovirt_password }}"
        headers:
          filter: true

    - name: Stop and Remove a VM
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ prefix }}-{{ item.name }}"
        state: absent
      with_items: "{{ nodes }}"
    
    - name: Cleanup IaaS auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
